// Generated by CoffeeScript 1.7.1
(function() {
  require(['helpers/jquery-2.1.1.min'], function() {
    var $h2;
    $h2 = $('h2');
    return $h2.each(function() {
      var $_this;
      $_this = $(this);
      $_this.addClass("md-inpage-anchor");
      $(".list-group").append("<li class='list-group-item'><a href='#" + $_this.text().split(' ').join('_') + "'>" + $_this.text() + "</a></li>");
      return $_this.attr('id', $_this.text().split(' ').join('_'));
    });
  });

}).call(this);
