// Generated by CoffeeScript 1.7.1
(function() {
  require(['helpers/jquery-2.1.1.min'], function() {
    var $h2;
    $h2 = $('h2');
    return $h2.each(function() {
      return $(".list-group").append("<li class='list-group-item'><a href='" + $(this).text() + "'>" + $(this).text() + "</a></li>");
    });
  });

}).call(this);
