// Generated by CoffeeScript 1.7.1
(function() {
  require(['helpers/jquery-2.1.1.min'], function() {
    var $h2;
    $h2 = $('h2');
    $h2.each(function() {
      var $_this;
      $_this = $(this);
      $_this.addClass("md-inpage-anchor");
      $(".list-group").append("<a class='list-group-item' href='#" + $_this.text().split(' ').join('_') + "'>" + $_this.text() + "</a>");
      return $_this.attr('id', $_this.text().split(' ').join('_'));
    });
    return $('.affix').affix({
      offset: {
        top: $('#nav').offset().top
      }
    });
  });

}).call(this);
